version: '3'

services:
  app:
    build: .
    container_name: video_tool
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - video_network

networks:
  video_network:
    driver: bridge 